-- Run from the repository root: nvim --headless -u NONE -l scripts/export.lua
local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
vim.opt.runtimepath:prepend(root)
local p = require("solitude.palette")
local ansi = require("solitude.terminal")

local function write(path, lines)
  local full = root .. "/" .. path
  vim.fn.mkdir(vim.fn.fnamemodify(full, ":h"), "p")
  assert(vim.fn.writefile(lines, full) == 0, "Could not write " .. full)
  print("Generated " .. path)
end

local kitty = { "# Generated by scripts/export.lua; edit lua/solitude/palette.lua." }
local roles = {
  { "background", p.bg }, { "foreground", p.fg },
  { "cursor", p.fg }, { "cursor_text_color", p.bg },
  { "selection_background", p.selection }, { "selection_foreground", "none" },
  { "active_border_color", p.sand }, { "inactive_border_color", p.border },
  { "active_tab_foreground", p.fg }, { "active_tab_background", p.bg_active },
  { "inactive_tab_foreground", p.fg_faint }, { "inactive_tab_background", p.bg_surface },
  { "tab_bar_background", p.bg_surface }, { "url_color", p.red },
}
for _, role in ipairs(roles) do
  kitty[#kitty + 1] = role[1] .. " " .. role[2]
end
for slot = 0, 15 do
  kitty[#kitty + 1] = "color" .. slot .. " " .. ansi[slot]
end
write("extras/kitty/solitude.conf", kitty)

-- A palette snippet layered over the existing Solitude Obsidian theme.
local variables = {
  ["background-primary"] = p.bg,
  ["background-primary-alt"] = p.bg_surface,
  ["background-secondary"] = p.bg_surface,
  ["background-secondary-alt"] = p.bg_subtle,
  ["background-modifier-border"] = p.border,
  ["background-modifier-border-hover"] = p.border_focus,
  ["background-modifier-hover"] = p.bg_hover,
  ["background-modifier-active-hover"] = p.bg_active,
  ["background-modifier-form-field"] = p.bg_subtle,
  ["text-normal"] = p.fg,
  ["text-muted"] = p.fg_muted,
  ["text-faint"] = p.fg_faint,
  ["text-accent"] = p.red,
  ["text-accent-hover"] = p.white,
  ["text-error"] = p.red,
  ["text-success"] = p.green,
  ["text-warning"] = p.yellow,
  ["interactive-accent"] = p.sand,
  ["interactive-accent-hover"] = p.fg,
  ["interactive-normal"] = p.border,
  ["interactive-hover"] = p.border_focus,
  ["interactive-success"] = p.green,
  ["link-color"] = p.red,
  ["link-color-hover"] = p.orange,
  ["link-external-color"] = p.orange,
  ["link-external-color-hover"] = p.orange,
  ["text-selection"] = p.selection,
  ["text-highlight-bg"] = p.selection,
  ["code-background"] = p.bg_subtle,
  ["code-normal"] = p.fg_soft,
  ["code-comment"] = p.fg_faint,
  ["code-function"] = p.fg,
  ["code-important"] = p.red,
  ["code-keyword"] = p.red,
  ["code-operator"] = p.orange,
  ["code-property"] = p.fg,
  ["code-punctuation"] = p.fg_faint,
  ["code-string"] = p.string,
  ["code-tag"] = p.red,
  ["code-value"] = p.orange,
  ["h1-color"] = p.fg,
  ["h2-color"] = p.fg_soft,
  ["h3-color"] = p.fg_muted,
  ["h4-color"] = p.fg_secondary,
  ["h5-color"] = p.fg_dim,
  ["h6-color"] = p.fg_dim,
  ["bold-color"] = p.red,
  ["italic-color"] = p.sand,
}
local bases = {
  ["00"] = p.bg, ["05"] = p.bg_subtle, ["10"] = p.bg_surface,
  ["20"] = p.bg_hover, ["25"] = p.bg_active, ["30"] = p.border,
  ["35"] = p.border_focus, ["40"] = p.fg_faint, ["50"] = p.fg_dim,
  ["60"] = p.fg_secondary, ["70"] = p.fg_soft, ["100"] = p.white,
}
for name, color in pairs(bases) do
  variables["color-base-" .. name] = color
end
local rgb = {}
for hex in p.sand:gmatch("%x%x") do
  rgb[#rgb + 1] = tostring(tonumber(hex, 16))
end
variables["interactive-accent-rgb"] = table.concat(rgb, ", ")
local css = {
  "/* Generated by scripts/export.lua; edit lua/solitude/palette.lua. */",
  ".theme-dark {",
}
local names = vim.tbl_keys(variables)
table.sort(names)
for _, name in ipairs(names) do
  css[#css + 1] = "  --" .. name .. ": " .. variables[name] .. ";"
end
css[#css + 1] = "}"

-- Override hard-coded syntax colors in the original Solitude stylesheet.
local syntax = {
  { "comment,prolog,doctype,cdata", ".cm-comment", "comment" },
  { "keyword,tag,atrule", ".cm-keyword, .cm-atom", "keyword" },
  { "string,char,attr-value", ".cm-string", "string" },
  { "function,class-name", ".cm-def", "function" },
  { "number,boolean,constant,symbol", ".cm-number, .cm-bool, .cm-constant", "value" },
  { "property,attr-name", ".cm-property", "property" },
  { "operator", ".cm-operator", "operator" },
  { "punctuation", ".cm-punctuation", "punctuation" },
}
for _, rule in ipairs(syntax) do
  local tokens = {}
  for token in rule[1]:gmatch("[^,]+") do
    tokens[#tokens + 1] = ".token." .. token
  end
  css[#css + 1] = ".theme-dark .markdown-rendered pre code :is(" .. table.concat(tokens, ", ") .. "),"
  css[#css + 1] = ".theme-dark .cm-s-obsidian :is(" .. rule[2] .. ") {"
  css[#css + 1] = "  color: var(--code-" .. rule[3] .. ");"
  css[#css + 1] = "}"
end
css[#css + 1] = ".theme-dark .cm-s-obsidian .cm-variableName { color: var(--text-muted); }"
css[#css + 1] = ".theme-dark .view-header-title::selection { background-color: var(--text-selection); color: var(--text-normal); }"
write("extras/obsidian/solitude-palette.css", css)
